[env:ttgo_geq_display_extr_partition]
# -------------------------------------------------------------------------------------------------------------
# Okay(ish ) June 23 2026 , after flashing two times , first flash the old build then 17 and repeat two times
# Audio sync lag on large matrix and MQTT  reconnect 
# -----------------------------------------------------------------------------------------------------------
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;#board = lilygo-t-display # https://docs.platformio.org/en/latest/boards/espressif32/lilygo-t-display.html
board = esp32dev
platform = ${esp32.platform}
platform_packages = ${esp32.platform_packages}
upload_speed = 921600
board_build.partitions = ${esp32.extreme_partitions}
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.f_flash = 80000000L
board_build.flash_mode = dio
monitor_filters = esp32_exception_decoder
custom_usermods = audioreactive TTGO_TDISPLAY_OUTPUT
build_flags =  ${common.build_flags} ${esp32.build_flags} ${esp32.AR_build_flags} ${common.debug_flags}
  -D WLED_DEBUG
  -D SERVERNAME="\"ALDIY-Tdis\""
  -D WLED_RELEASE_NAME=\"ttgo_geq_display_extr_partition\" 
  -D LEDPIN=12 #def 16 collides with TFT_DC
  -D UM_DisplayMatrix_Pins="TFT_MOSI,TFT_SCLK,TFT_CS,TFT_DC,TFT_RST,TFT_BL" #reserved pins
  ;; Display config (TFT_sSPI)
  -D USER_SETUP_LOADED
  -D DISABLE_ALL_LIBRARY_WARNINGS # because of "TOUCH_CS pin not defined, TFT_eSPI touch functions will not be available!" warning
  -D ST7789_DRIVER
  -D TFT_SDA_READ   # Display has a bidirectional SDA pin
  ;; -D CGRAM_OFFSET  keep for s3 320x170
  -D TFT_WIDTH=135
  -D TFT_HEIGHT=240
  -D TFT_MOSI=19
  -D TFT_SCLK=18
  -D TFT_CS=5
  -D TFT_DC=16
  -D TFT_RST=23
  -D TFT_BL=4        # backlight pin
  -D LOAD_GLCD
  -D SPI_FREQUENCY=40000000
  -D SPI_READ_FREQUENCY=6000000 # 6 MHz is the maximum SPI read speed for the ST7789V
  -D CLIENT_SSID=\"${sysenv.WIFI_SSID}\" -D CLIENT_PASS=\"${sysenv.WIFI_PASS}\"
lib_deps =
  ${esp32.lib_deps}
  ${esp32.AR_lib_deps}
  moononournation/GFX Library for Arduino @ 1.4.7
  ${esp32.AR_lib_deps}

